"""create reference and employee tables

Revision ID: aa75004fa9b3
Revises: 
Create Date: 2026-08-29 12:55:11.516236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa75004fa9b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('minor_unit', sa.Integer(), nullable=False),
    sa.CheckConstraint('minor_unit >= 0 AND minor_unit <= 4', name='ck_currency_minor_unit'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rank'),
    sa.UniqueConstraint('title')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('default_currency_code', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['default_currency_code'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code')
    )
    op.create_table('exchange_rate',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate_to_usd', sa.Float(), nullable=False),
    sa.CheckConstraint('rate_to_usd > 0', name='ck_exchange_rate_positive'),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('currency_code')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('job_level_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('base_salary >= 0', name='ck_employee_salary_non_negative'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['job_level_id'], ['job_level.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index('ix_employee_country_id', ['country_id'], unique=False)
        batch_op.create_index('ix_employee_department_id', ['department_id'], unique=False)
        batch_op.create_index('ix_employee_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_employee_job_level_id', ['job_level_id'], unique=False)
        batch_op.create_index('ix_employee_last_name', ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index('ix_employee_last_name')
        batch_op.drop_index('ix_employee_job_level_id')
        batch_op.drop_index('ix_employee_is_active')
        batch_op.drop_index('ix_employee_department_id')
        batch_op.drop_index('ix_employee_country_id')

    op.drop_table('employee')
    op.drop_table('exchange_rate')
    op.drop_table('country')
    op.drop_table('job_level')
    op.drop_table('department')
    op.drop_table('currency')
    # ### end Alembic commands ###
